### ISSUE TITLE
Inputs selection problem in last step

### ISSUE THREAD

**Issue by damiweb** [dotpay/PrestaShop-1.7#38]
I suggest to make selector more precise, because in current form it conflicts with any required input inside `#checkbox-payment-step` element. Besides when you make an assumption few line lower
https://github.com/dotpay/PrestaShop-1.7/blob/04dc621a133872fb884e00d5442bec3123e5332f/views/js/front.js#L21

that inputs you are looking for are checkbox'es, because they have property `checked` maybe it is better to select only checkboxes (eg. `[type="checkbox"]`).

https://github.com/dotpay/PrestaShop-1.7/blob/04dc621a133872fb884e00d5442bec3123e5332f/views/js/front.js#L18

https://github.com/dotpay/PrestaShop-1.7/blob/04dc621a133872fb884e00d5442bec3123e5332f/views/js/front.js#L42

**Comment by wpawel** [comment]
Please check it in: [v1.2.3](https://github.com/dotpay/PrestaShop-1.7/tree/v1.2.3)
