### ISSUE TITLE
Problem z COD

### ISSUE THREAD

**Issue by MasterOfPlaster** [dotpay/PrestaShop-1.7#41]
Po instalacji tego modułu występuje problem z modułem płatności za pobraniem. Nie aktywny button umolziwiajacy zakończenie procesu checkoutu. 

Trzeba najpierw zaakceptować Terms of conditions a później wybrać COD jako metode płatności 

Wersja presty 1.7.6

Wersja modułu 1.3.2

Po umożliwiweniu płatności przez dotpay po wybraniu przesyłki COD problem znikł ale przez to klient ma do wyboru płatność dotpay nawet jeżeli wybiera COD nie tak to powinno  działać

**Comment by wpawel** [comment]
Proszę sprawdzić zachowanie z najnowszą wersją modułu: [v1.4.0](https://github.com/dotpay/PrestaShop-1.7/releases/tag/v1.4.0).

**Comment by MasterOfPlaster** [comment]
> Proszę sprawdzić zachowanie z najnowszą wersją modułu: [v1.4.0](https://github.com/dotpay/PrestaShop-1.7/releases/tag/v1.4.0).

Tak teraz guzik "Zamówienie z obowiązkiem zapłąty" w przypadku COD działa poprawnie nawet jeżeli moduł nie jest włączony dla tego typu tranzakcji. Dziękuję
