### ISSUE TITLE
Przycisk 'Zamówienie z obowiązkiem zapłaty' nie aktywny

### ISSUE THREAD

**Issue by dpodwaln** [dotpay/PrestaShop-1.7#42]
Dotpay v. 1.3.2
Presta v. 1.7.8.2
Bez względu jaka metoda płatności jest wybrana moduł Dotpay loguje błąd: 
`NOT selected accept PayPro S.A. Regulations of Payments`
co deaktywuje przycisk zamówienia, aby aktywować przycisk należy wybrać płatność Dotpay odznaczyć akceptację regulaminu PayPro (domyślnie zaznaczone) i zaznaczyć go ponownie i od tego momentu przycisk zamówienia jest aktywny.

![image](https://user-images.githubusercontent.com/6186738/151962556-a468b43d-f545-497e-a4cc-9668d2ede86d.png)

**Comment by wpawel** [comment]
Gotowa jest poprawka w wersji modułu: [v1.4.0](https://github.com/dotpay/PrestaShop-1.7/releases/tag/v1.4.0).
