### ISSUE TITLE
Deprecated x2

### ISSUE THREAD

**Issue by patrykcode** [dotpay/PrestaShop-1.7#43]
Proszę o fixa w następnej aktualizacji, wyświetla błąd przed przekierowaniem do płatności
![dotpay](https://user-images.githubusercontent.com/19674444/161736530-42cae246-0642-4e86-a81f-6b8aef720915.png)

**Comment by wpawel** [comment]
taka zmiana była już wykonana w wersji [1.2.4](https://github.com/dotpay/PrestaShop-1.7/compare/v1.2.3...v1.2.4#diff-e49dba93233024873b160a7b30595763b70c46d59f25464dec38ce3da030fff6) w dniu 14.02.2022
