### ISSUE TITLE
Generowanie linku płatności dla REST API

### ISSUE THREAD

**Issue by fejmek** [dotpay/PrestaShop-1.7#46]
nvm, please delete

**Comment by fejmek** [comment]
przeciez nie mam racji z tym client side

**Comment by fejmek** [comment]
Doszedłem do takiego momentu:  
  
`$payment = new ModelPayment(new DotpayCustomer("--@--.pl", "--", "--"), new DotpayOrder(1336, 48.00, $this->context->currency->iso_code), 'test');`

 `$sdkLoader = Dotpay\Loader\Loader::load(`  
 `new Dotpay\Loader\Parser(dirname(__FILE__) . '/../../../dotpay/sdk/Dotpay/di.xml'),`  
 `new Dotpay\Loader\Parser(dirname(__FILE__) . '/../../../dotpay/classes/Dotpay/di.xml')`  
 `);`  
 `$paymentResource = $sdkLoader->get('PaymentResource');`  
 `$sellerResource = $sdkLoader->get('SellerResource');`  
 `$seller = new DotpaySeller(INT, "---");`  
 `$payment->setSeller($seller);`

 `$transaction = new Transaction($payment);`

 `$channel = new Channel(998, 'JALOGGMAS', $sdkLoader->get('Config'), $transaction, $paymentResource, $sellerResource);`

 `$registerOrderResource = $sdkLoader->get('RegisterOrder');`

 `print_r(`  
 `$registerOrderResource->create($channel)`  
 `);`  
  
i dostaje zwrotke `Dotpay API is forbidden to using  - Invalid username\/password`  
gdzie w request body, daje wszystkie potrzebne informacje...

**Comment by wpawel** [comment]
.
